'use client';

import { useEffect, useState } from 'react';
import { adminFetch } from './dashboard-api';
import { localizedDashboardAdminError } from '../lib/dashboard-errors';
import { computeGoogleDrivingRoute } from '../lib/google-maps-loader';
import { normalizeRoutePath, parseRouteAnchors } from '../lib/route-deviation.mjs';

const copy = {
  en: { eyebrow: 'ROUTE CONTROL', title: 'Job routes', subtitle: 'Save the Google Maps route used by each named job and tune deviation alerts.', name: 'Route name', link: 'Google Maps link', add: 'Add route', save: 'Save changes', cancel: 'Cancel', edit: 'Edit', remove: 'Delete', confirm: 'Delete this route?', distance: 'Off-route distance', duration: 'Off-route duration', seconds: 'seconds', km: 'km', settings: 'Deviation alert settings', settingsBody: 'A job is flagged when its recorded GPS remains farther than the distance threshold for at least the duration threshold.', saveSettings: 'Save settings', saved: 'Saved', empty: 'No job routes configured yet.', invalid: 'Please enter a route name and a valid Google Maps link.', failed: 'Could not load routes.', anchors: 'route points found', open: 'Open in Google Maps' },
  th: { eyebrow: 'ควบคุมเส้นทาง', title: 'เส้นทางงาน', subtitle: 'บันทึกลิงก์ Google Maps ของงานแต่ละชื่อ และปรับการแจ้งเตือนออกนอกเส้นทาง', name: 'ชื่อเส้นทาง', link: 'ลิงก์ Google Maps', add: 'เพิ่มเส้นทาง', save: 'บันทึกการแก้ไข', cancel: 'ยกเลิก', edit: 'แก้ไข', remove: 'ลบ', confirm: 'ลบเส้นทางนี้หรือไม่', distance: 'ระยะห่างนอกเส้นทาง', duration: 'ระยะเวลานอกเส้นทาง', seconds: 'วินาที', km: 'กม.', settings: 'ตั้งค่าการแจ้งเตือนออกนอกเส้นทาง', settingsBody: 'ระบบจะแจ้งเตือนเมื่อตำแหน่ง GPS อยู่ไกลกว่าเกณฑ์ระยะทางต่อเนื่องอย่างน้อยตามเกณฑ์เวลา', saveSettings: 'บันทึกการตั้งค่า', saved: 'บันทึกแล้ว', empty: 'ยังไม่ได้ตั้งค่าเส้นทางงาน', invalid: 'กรุณากรอกชื่อเส้นทางและลิงก์ Google Maps ที่ถูกต้อง', failed: 'ไม่สามารถโหลดเส้นทางได้', anchors: 'จุดเส้นทางที่พบ', open: 'เปิดใน Google Maps' },
};

export default function RoutesDashboard({ lang }) {
  const t = copy[lang];
  const [routes, setRoutes] = useState([]); const [settings, setSettings] = useState({ distanceKm: 0.5, durationSeconds: 60 });
  const [form, setForm] = useState({ routeName: '', googleMapsUrl: '' }); const [editing, setEditing] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  async function load() { setLoading(true); try { const result = await adminFetch('/api/admin/job-routes'); setRoutes(result.routes || []); setSettings(result.settings || settings); setError(''); } catch (value) { setError(localizedDashboardAdminError(value instanceof Error ? value.message : '', lang) || t.failed); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function reset() { setForm({ routeName: '', googleMapsUrl: '' }); setEditing(null); }
  async function submit(event) { event.preventDefault(); if (busy || !form.routeName.trim() || !form.googleMapsUrl.trim()) { if (!form.routeName.trim() || !form.googleMapsUrl.trim()) setError(t.invalid); return; } setBusy(true); setError(''); setMessage(''); try { let routePath = []; const parsedAnchors = parseRouteAnchors(form.googleMapsUrl); if (parsedAnchors.length >= 2) { try { routePath = normalizeRoutePath((await computeGoogleDrivingRoute(parsedAnchors)).path, 700); } catch (routeError) { console.error('[RoutesDashboard] Google driving route failed:', routeError); } } const result = await adminFetch(editing ? `/api/admin/job-routes/${encodeURIComponent(editing)}` : '/api/admin/job-routes', { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ ...form, routePath }) }); setRoutes(current => editing ? current.map(item => item.id === editing ? result.route : item) : [...current, result.route].sort((a, b) => a.routeName.localeCompare(b.routeName))); reset(); setMessage(t.saved); } catch (value) { setError(localizedDashboardAdminError(value instanceof Error ? value.message : '', lang)); } finally { setBusy(false); } }
  async function remove(id) { if (!window.confirm(t.confirm)) return; setError(''); setMessage(''); try { await adminFetch(`/api/admin/job-routes/${encodeURIComponent(id)}`, { method: 'DELETE' }); setRoutes(current => current.filter(item => item.id !== id)); } catch (value) { setError(localizedDashboardAdminError(value instanceof Error ? value.message : '', lang)); } }
  async function saveSettings(event) { event.preventDefault(); if (busy) return; setBusy(true); setError(''); setMessage(''); try { const result = await adminFetch('/api/admin/job-route-settings', { method: 'PUT', body: JSON.stringify(settings) }); setSettings(result.settings); setMessage(t.saved); } catch (value) { setError(localizedDashboardAdminError(value instanceof Error ? value.message : '', lang)); } finally { setBusy(false); } }
  return <main className="main routes-workspace" id="main-content" tabIndex={-1}>
    <div className="page-header"><div><div className="eyebrow">{t.eyebrow}</div><h1>{t.title}</h1><p>{t.subtitle}</p></div></div>
    {error ? <p className="error" role="alert">{error}</p> : null}{message ? <p className="success-message" role="status">{message}</p> : null}
    <section className="panel route-editor"><h2>{editing ? t.edit : t.add}</h2><form onSubmit={submit} className="route-form"><label>{t.name}<input value={form.routeName} onChange={event => setForm({ ...form, routeName: event.target.value })} placeholder="N21" maxLength={120} /></label><label>{t.link}<input type="url" value={form.googleMapsUrl} onChange={event => setForm({ ...form, googleMapsUrl: event.target.value })} placeholder="https://www.google.com/maps/dir/..." maxLength={2000} /></label><div className="route-form-actions"><button className="primary" disabled={busy} type="submit">{editing ? t.save : t.add}</button>{editing ? <button className="secondary" type="button" onClick={reset}>{t.cancel}</button> : null}</div></form></section>
    <section className="panel route-settings"><div><h2>{t.settings}</h2><p>{t.settingsBody}</p></div><form onSubmit={saveSettings} className="route-settings-form"><label>{t.distance}<span><input type="number" min="0.01" max="50" step="0.01" value={settings.distanceKm} onChange={event => setSettings({ ...settings, distanceKm: event.target.value })} /> {t.km}</span></label><label>{t.duration}<span><input type="number" min="1" max="86400" step="1" value={settings.durationSeconds} onChange={event => setSettings({ ...settings, durationSeconds: event.target.value })} /> {t.seconds}</span></label><button className="secondary" type="submit" disabled={busy}>{t.saveSettings}</button></form></section>
    <section className="panel route-list"><h2>{t.title}</h2>{loading ? <p>{t.failed}</p> : !routes.length ? <p>{t.empty}</p> : <div className="route-list-grid">{routes.map(route => <article className="route-row" key={route.id}><div><strong>{route.routeName}</strong><small>{route.anchors?.length || 0} {t.anchors}</small></div><a href={route.googleMapsUrl} target="_blank" rel="noreferrer">{t.open}</a><div className="row-actions"><button className="secondary small-button" type="button" onClick={() => { setError(''); setMessage(''); setEditing(route.id); setForm({ routeName: route.routeName, googleMapsUrl: route.googleMapsUrl }); }}>{t.edit}</button><button className="secondary small-button" type="button" onClick={() => void remove(route.id)}>{t.remove}</button></div></article>)}</div>}</section>
  </main>;
}
